// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/data-sources": {
            "get": {
                "description": "Retrieves all data sources connected on plugin with all information from the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data source"
                ],
                "summary": "Get all data sources connected on plugin smart templates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/DataSourceInformation"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/data-sources/{dataSourceId}": {
            "get": {
                "description": "Retrieves a data sources information with data source id passed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Data source"
                ],
                "summary": "Get a data sources information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Data source ID",
                        "name": "dataSourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DataSourceInformation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/pkg.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/pkg.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/pkg.HTTPError"
                        }
                    }
                }
            }
        },
        "/v1/reports": {
            "post": {
                "description": "Create a Report of existent template with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Create a Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Report Input",
                        "name": "reports",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateReportInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_report.Report"
                        }
                    }
                }
            }
        },
        "/v1/reports/{id}": {
            "get": {
                "description": "Get information of a Report passing the ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Get a Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_report.Report"
                        }
                    }
                }
            }
        },
        "/v1/reports/{id}/download": {
            "get": {
                "description": "Make a download of a Report passing the ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reports"
                ],
                "summary": "Download a Report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Report ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/v1/templates": {
            "get": {
                "description": "List all the templates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Get all templates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "XML, HTML, TXT and CSV",
                        "name": "outputFormat",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Description of template",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/Pagination"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_template.Template"
                                            }
                                        },
                                        "limit": {
                                            "type": "integer"
                                        },
                                        "page": {
                                            "type": "integer"
                                        },
                                        "total": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Template for reports with the input payload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create a Template for reports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Template file (.tpl)",
                        "name": "templateFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Output format (e.g., pdf, html)",
                        "name": "outputFormat",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Description of the template",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_template.Template"
                        }
                    }
                }
            }
        },
        "/v1/templates/{id}": {
            "get": {
                "description": "Get a template by id",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Get template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Template file (.tpl)",
                        "name": "templateFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Output format (e.g., pdf, html)",
                        "name": "outputFormat",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Description of the template",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_template.Template"
                        }
                    }
                }
            },
            "delete": {
                "description": "SoftDelete a Template with the input ID",
                "tags": [
                    "Templates"
                ],
                "summary": "SoftDelete a Template by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "description": "Update a template with the input payload",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Update a template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The authorization token in the 'Bearer\taccess_token' format. Only required when auth plugin is enabled.",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Template file (.tpl)",
                        "name": "templateFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Output format (e.g., pdf, html)",
                        "name": "outputFormat",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Description of the template",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/plugin-smart-templates_pkg_mongodb_template.Template"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "CreateReportInput": {
            "description": "CreateReportInput is the input payload to create a report.",
            "type": "object",
            "required": [
                "filters",
                "templateId"
            ],
            "properties": {
                "filters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "ledgerId": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "00000000-0000-0000-0000-000000000000"
                    ]
                },
                "templateId": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                }
            }
        },
        "DataSourceInformation": {
            "description": "DataSourceDetails is the data source details of database",
            "type": "object",
            "properties": {
                "externalName": {
                    "type": "string",
                    "example": "onboarding"
                },
                "id": {
                    "type": "string",
                    "example": "midaz_onboarding"
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/TableDetails"
                    }
                },
                "type": {
                    "type": "string",
                    "example": "postgresql"
                }
            }
        },
        "Pagination": {
            "description": "Pagination is the struct designed to store the pagination data of an entity list.",
            "type": "object",
            "properties": {
                "items": {},
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "TableDetails": {
            "description": "TableDetails is the struct of table information",
            "type": "object",
            "properties": {
                "fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['id'",
                        " 'name'",
                        " 'parent_account_id']"
                    ]
                },
                "name": {
                    "type": "string",
                    "example": "account"
                }
            }
        },
        "pkg.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "entityType": {
                    "type": "string"
                },
                "err": {},
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "plugin-smart-templates_pkg_mongodb_report.Report": {
            "type": "object",
            "properties": {
                "completedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "filters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "ledgerId": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['00000000-0000-0000-0000-000000000000'",
                        " '00000000-0000-0000-0000-000000000000']"
                    ]
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "type": "string",
                    "example": "processing"
                },
                "templateId": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "plugin-smart-templates_pkg_mongodb_template.Template": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Template Financeiro"
                },
                "fileName": {
                    "type": "string",
                    "example": "0196159b-4f26-7300-b3d9-f4f68a7c85f3_1744119295.tpl"
                },
                "id": {
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "outputFormat": {
                    "type": "string",
                    "example": "HTML"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2021-01-01T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:4005",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Plugin Smart Template",
	Description:      "This is a swagger documentation for plugin smart template",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
