#!/bin/bash

source "$PWD"/pkg/shell/colors.sh
source "$PWD"/pkg/shell/ascii.sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ $branch == "main" || $branch == "develop" || $branch == release/* ]]; then
  echo "${bold}You can't commit directly to protected branches"
  exit 1
fi