// Code generated by MockGen. DO NOT EDIT.
// Source: plugin-template-engine/components/worker/internal/adapters/mongodb/report (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=report.mongodb.mock.go --package=report . Repository
//

// Package report is a generated GoMock package.
package report

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// UpdateReportStatusById mocks base method.
func (m *MockRepository) UpdateReportStatusById(arg0 context.Context, arg1 string, arg2 uuid.UUID, arg3 string, arg4 time.Time, arg5 map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReportStatusById", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReportStatusById indicates an expected call of UpdateReportStatusById.
func (mr *MockRepositoryMockRecorder) UpdateReportStatusById(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReportStatusById", reflect.TypeOf((*MockRepository)(nil).UpdateReportStatusById), arg0, arg1, arg2, arg3, arg4, arg5)
}
