plugins:
  - path: "@semantic-release/commit-analyzer"
    preset: conventionalcommits
    parserOpts:
      noteKeywords:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
    releaseRules:
      - type: feat
        release: minor
      - type: perf
        release: minor
      - type: build
        release: minor
      - type: chore
        release: patch
      - type: ci
        release: patch
      - type: test
        release: patch
      - type: fix
        release: patch # to hotfix scenarios
      - type: refactor
        release: minor
      - type: docs
        release: patch
      - breaking: true
        release: major

  # Plugin to publish the GitHub release (no assets - changelog managed separately)
  - path: "@semantic-release/github"
    successComment: false
    failComment: false
    labels: []

  # Plugin to perform the backmerge between the 'main' and 'develop' branches
  - path: "@saithodev/semantic-release-backmerge"
    backmergeBranches:
      - from: main
        to: develop
    message: "chore(release): Preparations for next release [skip ci]"

  - path: "@semantic-release/exec"

branches:
  - name: main
  - name: develop
    prerelease: beta
  - name: release-candidate
    prerelease: rc