// Code generated by MockGen. DO NOT EDIT.
// Source: report.go
//
// Generated by this command:
//
//	mockgen -source=report.go -destination=report.mock.go -package=report
//

// Package report is a generated GoMock package.
package report

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, objectName string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, objectName)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, objectName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, objectName)
}

// Put mocks base method.
func (m *MockRepository) Put(ctx context.Context, objectName, contentType string, data []byte, ttl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, objectName, contentType, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockRepositoryMockRecorder) Put(ctx, objectName, contentType, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRepository)(nil).Put), ctx, objectName, contentType, data, ttl)
}

// MockS3Client is a mock of S3Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockS3Client) DownloadFile(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockS3ClientMockRecorder) DownloadFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockS3Client)(nil).DownloadFile), ctx, path)
}

// UploadFileWithContentType mocks base method.
func (m *MockS3Client) UploadFileWithContentType(ctx context.Context, path string, data []byte, contentType, ttl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFileWithContentType", ctx, path, data, contentType, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFileWithContentType indicates an expected call of UploadFileWithContentType.
func (mr *MockS3ClientMockRecorder) UploadFileWithContentType(ctx, path, data, contentType, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFileWithContentType", reflect.TypeOf((*MockS3Client)(nil).UploadFileWithContentType), ctx, path, data, contentType, ttl)
}

// UploadFileWithTTL mocks base method.
func (m *MockS3Client) UploadFileWithTTL(ctx context.Context, path string, data []byte, ttl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFileWithTTL", ctx, path, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFileWithTTL indicates an expected call of UploadFileWithTTL.
func (mr *MockS3ClientMockRecorder) UploadFileWithTTL(ctx, path, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFileWithTTL", reflect.TypeOf((*MockS3Client)(nil).UploadFileWithTTL), ctx, path, data, ttl)
}
