// Code generated by MockGen. DO NOT EDIT.
// Source: plugin-smart-templates/pkg/mongodb/report (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=report.mongodb.mock.go --package=report . Repository
//

// Package report is a generated GoMock package.
package report

import (
	context "context"
	http "plugin-smart-templates/pkg/net/http"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, collection string, record *Report, organizationID uuid.UUID) (*Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, collection, record, organizationID)
	ret0, _ := ret[0].(*Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, collection, record, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, collection, record, organizationID)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, collection string, id, organizationID uuid.UUID) (*Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, collection, id, organizationID)
	ret0, _ := ret[0].(*Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, collection, id, organizationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, collection, id, organizationID)
}

// FindList mocks base method.
func (m *MockRepository) FindList(ctx context.Context, collection string, filters http.QueryHeader) ([]*Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindList", ctx, collection, filters)
	ret0, _ := ret[0].([]*Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindList indicates an expected call of FindList.
func (mr *MockRepositoryMockRecorder) FindList(ctx, collection, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindList", reflect.TypeOf((*MockRepository)(nil).FindList), ctx, collection, filters)
}

// UpdateReportStatusById mocks base method.
func (m *MockRepository) UpdateReportStatusById(ctx context.Context, collection, status string, id uuid.UUID, completedAt time.Time, metadata map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReportStatusById", ctx, collection, status, id, completedAt, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReportStatusById indicates an expected call of UpdateReportStatusById.
func (mr *MockRepositoryMockRecorder) UpdateReportStatusById(ctx, collection, status, id, completedAt, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReportStatusById", reflect.TypeOf((*MockRepository)(nil).UpdateReportStatusById), ctx, collection, status, id, completedAt, metadata)
}
