// Code generated by MockGen. DO NOT EDIT.
// Source: reporter/v3/pkg/postgres (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen --destination=datasource.postgres.mock.go --package=postgres . Repository
//

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	reflect "reflect"

	model "github.com/LerianStudio/reporter/v3/pkg/model"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CloseConnection mocks base method.
func (m *MockRepository) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockRepositoryMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockRepository)(nil).CloseConnection))
}

// GetDatabaseSchema mocks base method.
func (m *MockRepository) GetDatabaseSchema(arg0 context.Context) ([]TableSchema, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseSchema", arg0)
	ret0, _ := ret[0].([]TableSchema)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseSchema indicates an expected call of GetDatabaseSchema.
func (mr *MockRepositoryMockRecorder) GetDatabaseSchema(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseSchema", reflect.TypeOf((*MockRepository)(nil).GetDatabaseSchema), arg0)
}

// Query mocks base method.
func (m *MockRepository) Query(arg0 context.Context, arg1 []TableSchema, arg2 string, arg3 []string, arg4 map[string][]any) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockRepositoryMockRecorder) Query(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockRepository)(nil).Query), arg0, arg1, arg2, arg3, arg4)
}

// QueryWithAdvancedFilters mocks base method.
func (m *MockRepository) QueryWithAdvancedFilters(arg0 context.Context, arg1 []TableSchema, arg2 string, arg3 []string, arg4 map[string]model.FilterCondition) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWithAdvancedFilters", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryWithAdvancedFilters indicates an expected call of QueryWithAdvancedFilters.
func (mr *MockRepositoryMockRecorder) QueryWithAdvancedFilters(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWithAdvancedFilters", reflect.TypeOf((*MockRepository)(nil).QueryWithAdvancedFilters), arg0, arg1, arg2, arg3, arg4)
}
