// Code generated by MockGen. DO NOT EDIT.
// Source: k8s-golang-addons-boilerplate/pkg/repository (interfaces: ExampleRepository)
//
// Generated by this command:
//
//	mockgen --destination=../../mocks/repository/example_mock.go --package=mock . ExampleRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	models "k8s-golang-addons-boilerplate/pkg/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExampleRepository is a mock of ExampleRepository interface.
type MockExampleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExampleRepositoryMockRecorder
	isgomock struct{}
}

// MockExampleRepositoryMockRecorder is the mock recorder for MockExampleRepository.
type MockExampleRepositoryMockRecorder struct {
	mock *MockExampleRepository
}

// NewMockExampleRepository creates a new mock instance.
func NewMockExampleRepository(ctrl *gomock.Controller) *MockExampleRepository {
	mock := &MockExampleRepository{ctrl: ctrl}
	mock.recorder = &MockExampleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExampleRepository) EXPECT() *MockExampleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExampleRepository) Create(input *models.ExampleInput) (*models.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", input)
	ret0, _ := ret[0].(*models.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExampleRepositoryMockRecorder) Create(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExampleRepository)(nil).Create), input)
}

// Delete mocks base method.
func (m *MockExampleRepository) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExampleRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExampleRepository)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockExampleRepository) Get(id string) (*models.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(*models.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExampleRepositoryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExampleRepository)(nil).Get), id)
}

// GetAll mocks base method.
func (m *MockExampleRepository) GetAll() ([]models.ExampleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]models.ExampleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockExampleRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockExampleRepository)(nil).GetAll))
}

// Update mocks base method.
func (m *MockExampleRepository) Update(id string, input *models.ExampleInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExampleRepositoryMockRecorder) Update(id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExampleRepository)(nil).Update), id, input)
}
